### ISSUE TITLE
test the model

### ISSUE THREAD

**Issue by Auroracccc** [ycq091044/BIOT#3]
Dear author
I encountered an issue while trying to reproduce your code run_multiclass_supervisied.py. During the testing process, I commented out the def prepare_HAR_dataloader(args) function and the trainer.fit(lightning_model, train_dataloaders=train_loader, val_dataloaders=val_loader) part. I used the Tuev dataset and the model EEG-PREST-16-channels.ckpt you provided for testing. However, I received an error message that says, "Restoring states from the checkpoint path at /home/ubuntu/MyFiles/BIOT-main/pretrained-models/EEG-PREST-16-channels.ckpt packages/pytorch_lightning/strategies/strategy.py", line 319, in load_model_state_dict self.lightning_module.load_state_dict(checkpoint["state_dict"]) KeyError: 'state_dict'.

Could you please tell me how to resolve this issue, or if there is a separate testing code available?

**Comment by ycq091044** [comment]
Could you try to run the example.py first? I provide example codes there to load the pre-trained models. If you have problem there, then please let me know.
