### ISSUE TITLE
Invitation for model integration into braindecode

### ISSUE THREAD

**Issue by bruAristimunha** [ycq091044/BIOT#4]
Hey @ycq091044 :)

I enjoyed reading your paper this week, and it left a strong impression on me. I'm eagerly awaiting its publication; in my humble opinion, it's an outstanding paper in EEG Decoding and with a lot of effort!

The tokenization process and your meticulous handling of various datasets are quite impressive. While examining the code, an idea crossed my mind – would you be open to the possibility of integrating your model into [braindecode](braindecode.org/)?

I'm aware of your involvement with the pyhealth library, which is more versatile. However, considering the widespread adoption of models like the example with Resnet, incorporating these exceptional models into various open-source platforms could be a valuable endeavour and potential booster of the use (and citation)!

I'm curious to know your thoughts. Would this be of interest to you?

**Comment by ycq091044** [comment]
Hi @bruAristimunha,

Thanks for reaching out. I am a bit busy in recent weeks. Will clean up the codes and contribute to braindecode in a few weeks.

**Comment by bruAristimunha** [comment]
Okay @ycq091044, I will wait your contribution for braindecode :)

**Comment by bruAristimunha** [comment]
Hey @ycq091044!

Pinging you after our conversation during NeurIPS.
