### ISSUE TITLE
IIIC_data used in the unsupervised 

### ISSUE THREAD

**Issue by marianyamukuru** [ycq091044/BIOT#9]
Hi,

Thanks a lot for this work. I was hoping to use it for my project but I'm having a hard time re-running the training for the unsupervised network. I requested access for the SHHS data, so while I wait on that, I wanted to use the IIIC_data but I'm not sure which of the datasets this data comes from. This can be found in the run_unsupervised_pretrain.py

```
root_prest = "/srv/local/data/IIIC_data/5M_IIIC_data/processed/s7n16"
root_shhs = "/srv/local/data/SHHS/processed"
```

**Comment by ycq091044** [comment]
The data is from my collaborators at Harvard Medical School. They have posted a link to download the data at https://bdsp.io/content/bdsp-sparcnet/1.1/. Let me know whether you can access the data.

**Comment by 1940653868** [comment]
https://bdsp.io/content/bdsp-sparcnet/1.1/. The dataset in the link is empty, just a txt file. We can not get the data now. I wonder whether we have other ways to get this dataset. Thanks for your answer.

**Comment by ycq091044** [comment]
Sure, you should request the data in this link. 
<img width="1234" alt="image" src="https://github.com/ycq091044/BIOT/assets/22296469/d840ebbb-8f07-4fc9-9ca2-8ca8f51c3604">

If you still cannot get the dataset, it might be possible to directly contact professor Westover or Jing Jin.
